### ISSUE TITLE
add to README - loading anaconda on Oscar

### ISSUE THREAD

**Issue by tdivoll** [brown-ccv/DSCoV-NapariWorkshop#1]

**Comment by tdivoll** [comment]
`module load anaconda/2022.05`
`conda init bash`

## close terminal and reopen

`conda activate /gpfs/runtime/opt/DSCoV_env`

**Comment by tdivoll** [comment]
@digicosmos86, I made the changes, just need you to add me to the repo so I can push and make a PR

**Comment by digicosmos86** [comment]
Thanks @tdivoll! Just added you :)
